CREATE TABLESPACE tp_tables DATAFILE 'TP_FILES_01.dbf' SIZE 500m; 

CREATE USER TP IDENTIFIED BY "tp" DEFAULT TABLESPACE tp_tables QUOTA
UNLIMITED ON tp_tables ;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO tp; 